### ISSUE TITLE
Add Minimum Age Setting and Form Validation

### ISSUE THREAD

**Issue by lisa-sa-li** [ieeeuoft/hackathon-template#157]
When are high school freshmen born?

**Comment by grahamhoyes** [comment]
Would make sense to define a minimum age setting, and subtract that from the event start date

**Comment by grahamhoyes** [comment]
https://stackoverflow.com/questions/49882526/validation-for-datefield-so-it-doesnt-take-future-dates-in-django

**Comment by grahamhoyes** [comment]
Add a minimum age in years to the settings file (eg 18), subtract from event start date and make that a validator on the application form

**Comment by grahamhoyes** [comment]
Done
