### ISSUE TITLE
Select2 Fields aren't focusable when invalid

### ISSUE THREAD

**Issue by grahamhoyes** [ieeeuoft/hackathon-template#175]
The application form can't be submitted when any of the select2 dropdowns are empty (since they're required), but since the actual select element is hidden it can't be focused on and doesn't alert the user. A not focusable error gets thrown in the console:

![image](https://user-images.githubusercontent.com/26036279/93405601-60ebcd00-f85b-11ea-9472-0a65efbf4b90.png)

We'd like some way of getting the HTML5 validation popup back, which means making the hidden select element focusable, though anything that alerts the user of the missing field would be acceptable.

**Comment by grahamhoyes** [comment]
https://stackoverflow.com/questions/18955835/select2-and-html5-form-validation

**Comment by Hangukkid** [comment]
_Hello, I wish to take an opportunity to resolve this issue._

**Comment by grahamhoyes** [comment]
> _Hello, I wish to take an opportunity to resolve this issue._

Go for it!

Since you'll need access to the application form, you'll have to change the date that applications close in the settings file to something in the future: https://github.com/ieeeuoft/hackathon-template/blob/develop/hackathon_site/hackathon_site/settings/__init__.py#L257.

After that, you can either create an account from the home page, or just create a superuser with `python manage.py createsuperuser`. If you create an account from the home page, the terminal will print out an email message that has an activation link you'll need to go to to activate the account first.

Once you have an activated account, you can get to the application from the link on /dashboard. We want it so that when the submit button is clicked with any of the select2 fields (any of the dropdowns) empty, a "this field is required" validation popup occurs like with the rest of the fields (if you're using Chrome, anyway).
