### ISSUE TITLE
Create new global variable (tuple) to hold chat room name + link

### ISSUE THREAD

**Issue by siddvader333** [ieeeuoft/hackathon-template#206]
- Create global variable in to hold tuple of the form: (chat_room_name, chat_room_link)
- Chat room name is of the following: Discord, Slack etc. and should be a string
- Insert new chat room name and link into email templates : https://github.com/ieeeuoft/hackathon-template/tree/develop/hackathon_site/registration/jinja2/registration/emails
- Insert new chat room name and link into other instances of hardcoded "Slack":  https://github.com/ieeeuoft/hackathon-template/blob/develop/hackathon_site/event/jinja2/event/dashboard_base.html

**Comment by grahamhoyes** [comment]
You'll have to modify (and possibly write) some tests to make sure those variables get included properly. Tests for the new email templates will be covered by #197, so you can modify those. Other email templates and the dashboard are tested throughout the registration and event app tests
