### ISSUE TITLE
Filtered Review Teams square members count

### ISSUE THREAD

**Issue by grahamhoyes** [ieeeuoft/hackathon-template#209]
A team can have a maximim of 4 users, but when viewing teams under Review > Teams, the team member count will be squared.
![image](https://user-images.githubusercontent.com/26036279/97088582-d9367280-15ff-11eb-9156-05332160674c.png)

This is because the count operations that happen in the filter end up doing another join, which squares the number of rows. Solution should be to do a count distinct.

**Comment by lzm9800** [comment]
Hi Graham, I would like to take this issue.

**Comment by grahamhoyes** [comment]
> Hi Graham, I would like to take this issue.

It's all yours!

The relevant admin class is here: https://github.com/ieeeuoft/hackathon-template/blob/develop/hackathon_site/review/admin.py#L154. This should involve just changing the Count annotation in `get_queryset` to have `distinct=True` as a parameter.

To verify that it works, create a few user accounts on the admin site. Create a team for them under Registration > Teams (not event > teams, that's something else). Then create an application for each of them from Registration > Applications. Once that's all done, under Review > Teams you can enable the "Not reviewed" filter to make sure the members count is correct instead of squared

**Comment by grahamhoyes** [comment]
You should also add a test case for this, below https://github.com/ieeeuoft/hackathon-template/blob/develop/hackathon_site/review/test_admin.py#L68. Something like `test_list_page_shows_team_member_count_with_filters`.

It would be similar to the test case that's there, just change `self.client.get(self.list_view)` to `self.client.get(f"{self.list_view}?reviewed=false")` to apply the filter.

I'd recommend writing that test first and making sure it fails, then updating the admin site and making sure the test passes. Instructions on running tests are here: https://github.com/ieeeuoft/hackathon-template#tests
